import { ArrowLeft, ArrowRight, LogOut, Mail, UserRound } from 'lucide-react';
import Link from 'next/link';
import { chatGPTSignOutPath, requireChatGPTUser } from '../chatgpt-auth';

export const dynamic = 'force-dynamic';

export default async function ProfilePage() {
  const user = await requireChatGPTUser('/profile');
  return (
    <main className="min-h-screen bg-[#dfe5db] px-5 py-10 text-[#514b46] md:px-10 md:py-16"><section className="mx-auto max-w-5xl border border-[#625b55]/14 bg-[#fbf8f2] shadow-[0_36px_100px_rgba(98,91,85,.16)]"><div className="flex items-center justify-between border-b border-[#625b55]/10 p-6 md:p-8"><Link href="/" className="inline-flex items-center gap-2 text-xs font-bold text-[#514b46]/55 transition hover:text-[#8f705e]"><ArrowLeft className="size-4" /> Back to portrait</Link><span className="grid size-10 place-items-center border border-[#a7826c]/55 font-heading text-xl text-[#7d695d]">H</span></div><div className="grid md:grid-cols-[0.75fr_1.25fr]"><div className="border-b border-[#625b55]/10 p-7 md:border-b-0 md:border-r md:p-10"><div className="grid size-20 place-items-center bg-[#dcc4b8] text-[#514b46]"><UserRound className="size-8" /></div><p className="mt-8 text-[10px] font-bold uppercase tracking-[0.2em] text-[#8f705e]">Personal space</p><p className="mt-3 text-sm leading-6 text-[#514b46]/48">Securely connected through ChatGPT. No separate Holyarted password is stored.</p></div><div className="p-7 md:p-10 lg:p-14"><h1 className="font-heading text-5xl leading-[0.95] tracking-[-0.04em] md:text-7xl">Welcome,<br /><span className="italic text-[#8f705e]">{user.displayName}.</span></h1><div className="mt-10 border-y border-[#625b55]/10 py-5"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#514b46]/38">Signed-in email</p><p className="mt-3 flex items-center gap-2 break-all text-sm text-[#514b46]/72"><Mail className="size-4 shrink-0 text-[#8f705e]" /> {user.email}</p></div><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/" className="inline-flex h-12 items-center justify-center gap-2 bg-[#625b55] px-6 text-xs font-bold text-[#f7f3ec]">Open portrait <ArrowRight className="size-4" /></Link><a href={chatGPTSignOutPath('/')} target="_top" className="inline-flex h-12 items-center justify-center gap-2 border border-[#625b55]/22 px-6 text-xs font-bold text-[#514b46]/68 transition hover:border-[#625b55]/50 hover:text-[#514b46]"><LogOut className="size-4" /> Sign out</a></div></div></div></section></main>
  );
}
