import { ArrowLeft, ArrowRight, LogOut, Mail, UserRound } from 'lucide-react';
import Link from 'next/link';
import { chatGPTSignOutPath, requireChatGPTUser } from '../chatgpt-auth';

export const dynamic = 'force-dynamic';

export default async function ProfilePage() {
  const user = await requireChatGPTUser('/profile');
  return (
    <main className="min-h-screen bg-[#0d0d12] px-5 py-10 text-[#f5f0e8] md:px-10 md:py-16"><section className="mx-auto max-w-5xl border border-white/15 bg-[#18131b] shadow-[0_36px_100px_rgba(0,0,0,.38)]"><div className="flex items-center justify-between border-b border-white/10 p-6 md:p-8"><Link href="/" className="inline-flex items-center gap-2 text-xs font-bold text-white/55 transition hover:text-[#d9bb91]"><ArrowLeft className="size-4" /> Back to portrait</Link><span className="grid size-10 place-items-center border border-[#c8a77a]/65 font-heading text-xl text-[#d9bb91]">H</span></div><div className="grid md:grid-cols-[0.75fr_1.25fr]"><div className="border-b border-white/10 p-7 md:border-b-0 md:border-r md:p-10"><div className="grid size-20 place-items-center bg-[#c8a77a] text-[#0d0d12]"><UserRound className="size-8" /></div><p className="mt-8 text-[10px] font-bold uppercase tracking-[0.2em] text-[#d9bb91]">Personal space</p><p className="mt-3 text-sm leading-6 text-white/45">Securely connected through ChatGPT. No separate Holyarted password is stored.</p></div><div className="p-7 md:p-10 lg:p-14"><h1 className="font-heading text-5xl leading-[0.95] tracking-[-0.04em] md:text-7xl">Welcome,<br /><span className="italic text-[#d9bb91]">{user.displayName}.</span></h1><div className="mt-10 border-y border-white/10 py-5"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/35">Signed-in email</p><p className="mt-3 flex items-center gap-2 break-all text-sm text-white/70"><Mail className="size-4 shrink-0 text-[#d9bb91]" /> {user.email}</p></div><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/" className="inline-flex h-12 items-center justify-center gap-2 bg-[#c8a77a] px-6 text-xs font-bold text-[#0d0d12]">Open portrait <ArrowRight className="size-4" /></Link><a href={chatGPTSignOutPath('/')} target="_top" className="inline-flex h-12 items-center justify-center gap-2 border border-white/20 px-6 text-xs font-bold text-white/65 transition hover:border-white/50 hover:text-white"><LogOut className="size-4" /> Sign out</a></div></div></div></section></main>
  );
}
